# Generated by Django 3.1.6 on 2021-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=None)),
                ('item_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bid',
            name='currentprice',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shortdescription',
        ),
        migrations.AddField(
            model_name='bid',
            name='user_id',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='item_id',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
