# Generated by Django 3.1.6 on 2021-03-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210309_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='item_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
