# Generated by Django 3.1.6 on 2021-03-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210310_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
