# Generated by Django 3.1.6 on 2021-03-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210310_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.item'),
        ),
    ]
