# Generated by Django 3.1.6 on 2021-03-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210311_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item_id',
            field=models.IntegerField(blank=True),
        ),
    ]
