# Generated by Django 3.1.6 on 2021-03-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210312_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
