# Generated by Django 3.1.6 on 2021-03-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210315_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
