# Generated by Django 3.1.6 on 2021-03-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210320_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
