# Generated by Django 3.1.6 on 2021-03-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210322_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
