# Generated by Django 3.1.6 on 2021-03-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210325_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item_id',
            new_name='itemid',
        ),
    ]
