# Generated by Django 3.1.6 on 2021-03-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210325_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='itemid',
            new_name='item_id',
        ),
    ]
