# Generated by Django 3.1.6 on 2021-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210325_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
