# Generated by Django 3.1.6 on 2021-03-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20210326_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='defaultimage',
            field=models.ImageField(default='noimage.jpg', upload_to=''),
        ),
    ]
