# Generated by Django 3.1.6 on 2021-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_item_defaultimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='defaultimage',
            field=models.ImageField(default='/noimage.jpg', upload_to=''),
        ),
    ]
