# Generated by Django 3.1.6 on 2021-03-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20210327_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='defaultimage',
            field=models.ImageField(default='/noimage.jpg', upload_to='test'),
        ),
    ]
