# Generated by Django 3.1.6 on 2021-03-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20210327_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='defaultimage',
        ),
    ]
