# Generated by Django 3.1.6 on 2021-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_remove_item_defaultimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='startingbid',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=6),
        ),
    ]
