# Generated by Django 3.1.6 on 2021-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20210327_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='startingbid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
    ]
